title = "crab2313's blog"
base_url = "https://crab2313.github.io"
compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true

theme = "even"
taxonomies = [
    # You can enable/disable feeds
    {name = "tags", feed = true},
]

[extra]
# This is the default menu
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://github.com/crab2313", name = "Github"},
]

even_title = "crab2313's blog"
